name: Validate Fastlane

on: push

jobs:
  validate:
    name: Validate Fastlane
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v1